### ISSUE TITLE
翻译过的地方有小竖线无法消退

### ISSUE THREAD

**Issue by yueduz** [tuberry/light-dict#12]
![2021-03-06 09-46-10 的屏幕截图](https://user-images.githubusercontent.com/1448159/110190979-1c7fd800-7e61-11eb-9eae-759ab581adb0.png)

**Comment by tuberry** [comment]
无法复现。什么主题？

**Comment by yueduz** [comment]
我用了点阵字关系

**Comment by tuberry** [comment]
无法复现。你可以尝试：1）从 github 安装并重启后看问题是否还存在； 2）提供更详细的环境和复现步骤，为防潜在的冲突建议先关闭其他插件再测试或添加一个新用户测试。

**Comment by yueduz** [comment]
light-dict版本： 64
系统： archlinux
gnome: 3.38.4
使用默认主题换了字体还是会有。

**Comment by tuberry** [comment]
64？应该是46吧，现在部件复用了 IBus 候选框的样式，也许与此有关。如果修改过 IBus 样式先复原看看。我新建了用户从 E.G.O 安装测试仍旧无法复现。请提供详细的复现步骤。

**Comment by yueduz** [comment]
我用dconf 清除 light-dict 配置后好了。一个额外的建议，当禁止编辑配置本框时也禁止聚焦文本框。我一曾以为输入法出问题。

tuberry <notifications@github.com> 于2021年3月8日周一 下午6:24写道：

**Comment by tuberry** [comment]
1. 可以的话提供一下能复现的配置
2. 禁止编辑时输入一般会有键盘提示音，而且无法聚焦也无法选中或复制。预期行为。

**Comment by yueduz** [comment]
还是会出现，还没有找到原因

tuberry ***@***.***> 于2021年3月9日周二 下午11:08写道：

**Comment by yueduz** [comment]
![2021-03-10 12-44-57 的屏幕截图](https://user-images.githubusercontent.com/1448159/110577856-7d2f4d80-819e-11eb-8c67-5a16b92b9232.png)
就是这个问题，当弹出的正则不匹配时，就会有竖线。当匹配过一次后，不在出现。

**Comment by tuberry** [comment]
未复现，但我提交了一个可能的修复。你可以试试

**Comment by yueduz** [comment]
新的提交也没有用。是这样的，在系统启动后，一次都没有匹配时才会有竖线。匹配过一次后就不会再出现了。

tuberry ***@***.***> 于2021年3月10日周三 下午4:13写道：

**Comment by tuberry** [comment]
还是无法复现。这样吧，如果你新建用户或者用虚拟机100%复现请提供测试用的最小配置`dconf dump '/org/gnome/shell/extensions/light-dict/' > ld.dconf` 。觉得特别影响使用的话你可以安装上一个版本。

**Comment by yueduz** [comment]
新用户，100%复现。

[ld.zip](https://github.com/tuberry/light-dict/files/6121724/ld.zip)

补充一点信息，我使用的基于xorg的Gnome，我使用了N卡后，wayland模式就不见了。我使用fcitx输入法， 不过我测试时换了ibus还是有竖线，目前与卸载了ibus。

**Comment by tuberry** [comment]
OK，我用扩展网站上的版本(46)和你的设置文件在Xorg下复现了，但是用Git上的版本无法复现。所以应该已经修好了。你再试试？
