### ISSUE TITLE
为什么git上的版本号总是没有https://extensions.gnome.org上的新,总是被覆盖

### ISSUE THREAD

**Issue by yueduz** [tuberry/light-dict#14]
为什么不在git上使用一个更新的版本号

**Comment by tuberry** [comment]
因为我懒 :)。但是按照 README 从 Github 安装版本号是会[自动](https://github.com/tuberry/light-dict/blob/master/Makefile#L34)更新的。如果没有，可能你的网络访问EGO时出现了问题。
