### ISSUE TITLE
ocr 原文返回，已经加了-d zh-cn 参数

### ISSUE THREAD

**Issue by yueduz** [tuberry/light-dict#15]
![2021-09-04 11-19-40 的屏幕截图](https://user-images.githubusercontent.com/1448159/132080773-3e2dfc22-6564-45e0-a359-5a11502873d2.png)

我使用的是gnome 40.4.0,从git安装的版本直接不能启用，已经使用 `git checkout 40` 。

从https://extensions.gnome.org 安装的ocr 原文返回，已经加了-d zh-cn 参数

**Comment by tuberry** [comment]
> 我使用的是gnome 40.4.0,从git安装的版本直接不能启用，已经使用 git checkout 40 。

`不能启用`对于解决`不能启用`帮助不大，还要有详细复现步骤+日志/报错信息。

> 从https://extensions.gnome.org 安装的ocr 原文返回，已经加了-d zh-cn 参数

因为上游 [python-googletrans](https://github.com/ssut/py-googletrans#note-on-library-usage) 采用的是谷歌翻译的免费服务，并不保证一定可用。
