### ISSUE TITLE
OCR翻译接口可以自定义吗？Google使用不了

### ISSUE THREAD

**Issue by yueduz** [tuberry/light-dict#17]

**Comment by tuberry** [comment]
我没放 issue 模板，但是希望其中应该有：1.环境 2.复现步骤 3.复现结果 4.预期行为。以及 Feature Request 和 Bug Report 应该分开。这样能节省你我的时间。~~就"Google使用不了“这个描述本身对我来说就是问题，就像上个 issue 中的[说法](https://github.com/tuberry/light-dict/issues/15#issuecomment-912979595)，我实在不擅长推理有问题的问题。~~

**Comment by tuberry** [comment]
如果指是 OCR 里带的 Google 翻译，抱歉我差不多忘了有这功能。

首先 OCR 不应该管翻译的事，这也是当时心血来潮随手加的，其次 [py-googletrans](https://github.com/ssut/py-googletrans) 在我测试时存在依赖问题而无法使用，因此我决定移除这个接口。

如果你想继续使用 Google 翻译 OCR 的结果，我建议使用 [translate-shell](https://github.com/soimort/translate-shell)，加一个即时命令`Trans`(例如，`trans -b -- LDWORD`)，然后将 OCR 的参数设为 `-n Trans`。

至于其它翻译接口，我个人对此兴趣不大。大部分翻译服务要求密钥或口令之类的。如果有需要，我建议自行申请并写个小脚本（通常官方会有文档作为参考）作为命令行工具后依照上述方法添加为即时命令使用。

**Comment by yueduz** [comment]
我原本有一个可用的即时命令名字是“baidu”，然后将 OCR 的参数设为 “-n baidu“，多数时候没有任何输出，不弹出任何窗口，有时候，他弹出如图信息。在你给出是示例中，两个连杠“--”是什么意思？
gnome版本： 41.1
窗口系统：xorg
light-dict版本：65

![2021-11-15 18-09-31 的屏幕截图](https://user-images.githubusercontent.com/1448159/141763131-66171c93-f9dc-46e3-9c14-58b5a53f774a.png)

**Comment by tuberry** [comment]
> 多数时候没有任何输出，不弹出任何窗口，

检查命令的`显示结果`是否已启用

> 有时候，他弹出如图信息。

这个指调用 GNOME Shell 本身的 DBus 出现问题，但我没复现这种边界情况（需要稳定的复现步骤）。我会考虑输出更详细的错误信息

> 两个连杠“--”是什么意思？

一种命令行约定，表示参数终结。参见这个[答案](https://unix.stackexchange.com/a/11382)或 `man bash` OPTIONS 一节

此外，你可以新建用户并从Github 安装最新版本测试，如果仍不行，请提供最小可复现配置。
