### ISSUE TITLE
使用本地词典时有冗余的行

### ISSUE THREAD

**Issue by inoton** [tuberry/light-dict#18]
扩展非常好用，大赞！
使用中碰到一个问题，希望网友们提供帮助。感谢！

### 问题
当使用本地词典时冗余 6 行输出。
希望从“1 definition found” 开始的 6 后行都不显示，不知道有没有办法做到？

### 设置如下图
![image](https://user-images.githubusercontent.com/54309560/147356132-1424e5c8-3559-41ce-b161-4c37c6ae11f2.png)

![Screenshot from 2021-12-24 20-31-52](https://user-images.githubusercontent.com/54309560/147356201-c0277419-dd04-4d5a-8775-1489c40f4331.png)

![Screenshot from 2021-12-24 20-35-47](https://user-images.githubusercontent.com/54309560/147356543-72068d55-0a28-4bfd-b6a6-a149ffc1e798.png)

**Comment by tuberry** [comment]
喜欢的话可以推荐给亲友。(x

只有显示内容与命令在终端运行的结果不符才算本扩展的问题。

此处的 sh 命令只支持非常有限的 sh 功能集，其中甚至不包括管道（将解析为字面值）。

因此，这里建议一律将命令包装为 bash 或其它脚本后放到用户 PATH 下使用，除非它本身非常简单（如，`echo LDWORD`）。
