### ISSUE TITLE
Error wen update or reinstall extension

### ISSUE THREAD

**Issue by Yoannjap** [tuberry/light-dict#2]
Hey, I update your addon to last version.

Error and here is what appears :

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Stack trace:
  _rowMaker@/home/yoannj-ubuntu/.local/share/gnome-shell/extensions/light-dict@tuberry.github.io/prefs.js:390:25
  _init/<@/home/yoannj-ubuntu/.local/share/gnome-shell/extensions/light-dict@tuberry.github.io/prefs.js:291:28
  _init@/home/yoannj-ubuntu/.local/share/gnome-shell/extensions/light-dict@tuberry.github.io/prefs.js:290:52
  _init@/home/yoannj-ubuntu/.local/share/gnome-shell/extensions/light-dict@tuberry.github.io/prefs.js:53:28
  buildPrefsWidget@/home/yoannj-ubuntu/.local/share/gnome-shell/extensions/light-dict@tuberry.github.io/prefs.js:41:12
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by tuberry** [comment]
The new config is not compatible with old version. 
 Please run `gnome-extensions reset light-dict@tuberry.github.io` to remove old config file then reinstall it. Also if you have `dconf-editor` installed, you could keep some useful config at `/org/gnome/shell/extensions/light-dict/` before resetting.

**Comment by Yoannjap** [comment]
Hey, thanks for your reply.

I did run the command `gnome-extensions reset light-dict@tuberry.github.io`, than reinstalled the extension, but I always get the same error problem :
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Stack trace:
  _rowMaker@/home/yoannj-ubuntu/.local/share/gnome-shell/extensions/light-dict@tuberry.github.io/prefs.js:390:25
  _init/<@/home/yoannj-ubuntu/.local/share/gnome-shell/extensions/light-dict@tuberry.github.io/prefs.js:291:28
  _init@/home/yoannj-ubuntu/.local/share/gnome-shell/extensions/light-dict@tuberry.github.io/prefs.js:290:52
  _init@/home/yoannj-ubuntu/.local/share/gnome-shell/extensions/light-dict@tuberry.github.io/prefs.js:53:28
  buildPrefsWidget@/home/yoannj-ubuntu/.local/share/gnome-shell/extensions/light-dict@tuberry.github.io/prefs.js:41:12
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  `

**Comment by tuberry** [comment]
It seems that `gnome-extensions reset light-dict@tuberry.github.io ` doesn't clear all settings. Please follow those steps:
1. uninstall this extenion and install `dconf-editor;
2. open `dconf-editor` and erase any keys under `/org/gnome/shell/extensions/light-dict/`
3. install this extension.

I install this extension in a fresh account and get no errors. 
Sorry about the inconvenience caused in the updates but I think it wont happen again.
