### ISSUE TITLE
Gnome 43

### ISSUE THREAD

**Issue by lankymagnetize** [tuberry/light-dict#20]
A wonderful extension. It does not work on Gnome 43 on Ubuntu 22.10.

**Comment by tuberry** [comment]
Works for me. Did you try re-login?

If so, any related logs / screenshots?
```shell
journalctl -fo cat /usr/bin/gnome-shell # see logs
```

By the way, the configuration may not be compatible with the old version, please check if the settings are correct.

**Comment by lankymagnetize** [comment]
Thanks for the hint. I had to delete the extension and then reinstall it. Now it works perfect. Sorry for not testing this before.
