### ISSUE TITLE
[Question] How to render HTML output?

### ISSUE THREAD

**Issue by nbCloud91** [tuberry/light-dict#21]
I use sdcv with Wiktionary StarDict to get the definition of words. Sample output (there are no line breaks etc) is like:

```
-->English-English Wiktionary dictionary (en-en)
-->new

<i>adj</i><br><ol><li>Recently made, or created.</li><li>Of recent origin; having taken place recently.</li><li>Additional; recently discovered.</li><li>Current or later, as opposed to former.</li><li>Used to distinguish something established more recently, named after something or some place previously existing.</li><li>In original condition; pristine; not previously worn or used.</li><li>Refreshed, reinvigorated, reformed.</li><li>Newborn.</li><li>Strange, unfamiliar or not previously known.</li><li>Recently arrived or appeared.</li><li>Inexperienced or unaccustomed at some task.</li><li>(of a period of time) Next; about to begin or recently begun.</li></ol><br><i>adv</i><br><ol><li>Newly (especially in composition).</li><li>As new; from scratch.</li></ol><br><i>noun</i><br><ol><li>Things that are new.</li><li>(Australia) A kind of light beer.</li><li>(UK, naval slang) A naval cadet who has just embarked on training.</li></ol><br><i>verb</i><br><ol><li>(programming) Synonym of new up</li><li>(obsolete) To make new; to recreate; to renew.</li></ol>
```
But if it is rendered, it should look like: 

> -->English-English Wiktionary dictionary (en-en)
> -->new
>
> <i>adj</i><br><ol><li>Recently made, or created.</li><li>Of recent origin; having taken place recently.</li><li>Additional; recently discovered.</li><li>Current or later, as opposed to former.</li><li>Used to distinguish something established more recently, named after something or some place previously existing.</li><li>In original condition; pristine; not previously worn or used.</li><li>Refreshed, reinvigorated, reformed.</li><li>Newborn.</li><li>Strange, unfamiliar or not previously known.</li><li>Recently arrived or appeared.</li><li>Inexperienced or unaccustomed at some task.</li><li>(of a period of time) Next; about to begin or recently begun.</li></ol><br><i>adv</i><br><ol><li>Newly (especially in composition).</li><li>As new; from scratch.</li></ol><br><i>noun</i><br><ol><li>Things that are new.</li><li>(Australia) A kind of light beer.</li><li>(UK, naval slang) A naval cadet who has just embarked on training.</li></ol><br><i>verb</i><br><ol><li>(programming) Synonym of new up</li><li>(obsolete) To make new; to recreate; to renew.</li></ol>

Is there any way to show the result in properly formatted way? Currently, I just get the raw HTML.

**Comment by tuberry** [comment]
As a terminal tool, it should have the option to output as plain text to be useful.
If not, you can search how to render html in the terminal like `cat a.html | lynx --dump --stdin` or look for some formatting tools like `pandoc`.
By the way, it supports rendering Pango Markup so tools like [html2pango](https://docs.rs/html2pango/latest/html2pango/index.html) are also worth considering.

**Comment by nbCloud91** [comment]
Thanks for the tip, I have tried to use output with pango markup instead of HTML, but saw a new issue crop up.
https://github.com/tuberry/light-dict/issues/22#issue-1577894648
