### ISSUE TITLE
Bug Gnome 43.5

### ISSUE THREAD

**Issue by antonio24073** [tuberry/light-dict#23]
Hi,

It doesn't work in manjaro gnome 43.5.
Here is the log:

```
TypeError: method Gtk.CssProvider.load_from_data: At least 2 arguments required, but only 1 passed

Stack trace:
  fillPreferencesWindow@/home/antonio/.local/share/gnome-shell/extensions/light-dict@tuberry.github.io/prefs.js:29:14
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:368:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:401:34
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

Thank you

**Comment by tuberry** [comment]
Already fixed since https://github.com/tuberry/light-dict/commit/16c9702c5b0fb9e9f4d157a68f6e83557433a34f (`git diff 16c9702^ 16c9702 -M -- light-dict@tuberry.github.io/prefs.js src/prefs.js`):
```diff
diff --git a/light-dict@tuberry.github.io/prefs.js b/src/prefs.js
similarity index 99%
rename from light-dict@tuberry.github.io/prefs.js
rename to src/prefs.js
index 3158c14..afd925a 100644
--- a/light-dict@tuberry.github.io/prefs.js
+++ b/src/prefs.js
@@ -29,7 +29,7 @@ function fillPreferencesWindow(win) {
     provider.load_from_data(`.ld-drop-up { background: linear-gradient(to bottom, #000a 0%, #0000 35%); }
                             .ld-drop-down { background: linear-gradient(to bottom, #0000 65%, #000a 100%); }
                             .ld-drop-up-dark { background: linear-gradient(to bottom, #fffa 0%, #fff0 35%); }
-                            .ld-drop-down-dark { background: linear-gradient(to bottom, #fff0 65%, #fffa 100%); }`);
+                            .ld-drop-down-dark { background: linear-gradient(to bottom, #fff0 65%, #fffa 100%); }`, -1);
     Gtk.StyleContext.add_provider_for_display(Gdk.Display.get_default(), provider, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION);
     Gtk.IconTheme.get_for_display(Gdk.Display.get_default()).add_search_path(Me.dir.get_child('icons').get_path());
     [
```
Please  backport it to fix the bug by yourself, due to poor support for old GNOME versions.
```
The latest and supported version should only work on the most current stable version of GNOME Shell.
```

**Comment by antonio24073** [comment]
thank you very much to fix this bug, but in the page https://extensions.gnome.org/extension/2959/light-dict/ when I clicked on/off it's not working yet.

The latest and supported version should only work on the most current stable version of GNOME Shell. -> you can try gnome boxes, it is very fast to create VMs to your old releases, would you fix this in 10 minutes in all gnomes.

Thank you.

**Comment by tuberry** [comment]
> thank you very much to fix this bug, but in the page [extensions.gnome.org/extension/2959/light-dict](https://extensions.gnome.org/extension/2959/light-dict/) when I clicked on/off it's not working yet.

Just modify that file according to the diff to fix.  The version on EGO is not updated.

> The latest and supported version should only work on the most current stable version of GNOME Shell. -> you can try gnome boxes, it is very fast to create VMs to your old releases, would you fix this in 10 minutes in all gnomes.

Sorry, it is about subjective agency, not methodology. TBH, that line is just an outline of guideline 2 in Mpris Indicator Button's [bug-reports wiki](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/Bug-Reports-and-Feature-Requests#bug-reports).

**Comment by antonio24073** [comment]
Thank you
