### ISSUE TITLE
some features

### ISSUE THREAD

**Issue by antonio24073** [tuberry/light-dict#24]
Hi, 
Maybe you can do some default popup commands like google translate with translate-shell
```
trans :pt -b LDWORD
```
And the popup could be clickable to let copy.

This would greatly popularize your plugin and are simple changes

**Comment by tuberry** [comment]
>  Maybe you can do some default popup commands like google translate with translate-shell

`translate-shell` is coded as a [default in Swift commands](https://github.com/tuberry/light-dict/blob/bd6aa2d41e0f78a33d7c5c9125bcaac2707ccd32/res/schemas/org.gnome.shell.extensions.light-dict.gschema.xml#L91) to avoid confusion for users who install and then find that there aren't any popups like the one shown in the screenshot. So the default is for reference only, but not a common set of use cases for all (hard to find).

> And the popup could be clickable to let copy.

It is designed as a singleton tooltip-like widget for sanity, as explained [here](https://github.com/tuberry/light-dict/issues/3#issuecomment-1207386376). You can middle-click to copy all the content or launch an app for any other advanced operations, which are out of the scope of **`Light`**.
