### ISSUE TITLE
Error in latest version

### ISSUE THREAD

**Issue by nixuri** [tuberry/light-dict#25]
i installed lastest version
it return this error
![image](https://github.com/tuberry/light-dict/assets/20394645/0e6730f5-ce66-4aae-8f9c-ae042c7a2600)

SyntaxError: expected property name, got '{'

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
Ubuntu 20.04
Gnome 3.36.8

**Comment by tuberry** [comment]
Sorry, the [latest and supported](https://github.com/tuberry/light-dict#manual) version should only work on the most current stable version of GNOME Shell. :)

You could try to install the very old version from https://extensions.gnome.org/extension/2959/light-dict/ or `git tag`, however, it is recommended to upgrade to Ubuntu 23.04 / GNOME 44 for better features and support.
