### ISSUE TITLE
[Question] How to render terminal highlight output format

### ISSUE THREAD

**Issue by anhng195** [tuberry/light-dict#27]
I started using the Light-Dict today, it's very impressive. However, I encountered an issue with the 'trans' command output—there are bold and underlined text that I'm unsure how to display properly in the Light-Dict output window. Can you assist me with this? Thank you!
![shell output](https://i.ibb.co/wSny7dp/Screenshot-from-2023-11-17-19-09-52.png)

**Comment by tuberry** [comment]
The ANSI escape codes should first be converted to Pango Markups for rendering. You can try some commands like [ansifilter](https://gitlab.com/saalen/ansifilter):
```bash
trans -- LDWORD | ansifilter -Mcf
```
or just discard ANSI codes:
```bash
trans -no-ansi -- LDWORD
```

**Comment by anhng195** [comment]
It worked, thank you!
