### ISSUE TITLE
命令在气泡命令中无效

### ISSUE THREAD

**Issue by yueduz** [tuberry/light-dict#28]
```echo ok  |  festival --tts ```
这个命令在终端可以正常发声.在弹出中正常发声,但需要打开显示结果才行.
在气泡左键命令和右键命令中无声,
![image](https://github.com/tuberry/light-dict/assets/1448159/e162661e-edba-4c11-bf67-fd47b909aabf)

light-dict: 75

```
                  .o+`                   ----------- 
                 `ooo/                   OS: Arch Linux x86_64 
               `+oooooo:                 Kernel: 6.6.1-arch1-1 
               -+oooooo+:                Uptime: 4 mins 
            `/++++/+++++++:              Shell: zsh 5.9 
          `/+++ooooooooooooo/`           DE: GNOME 45.1 
         ./ooosssso++osssssso+`          WM: Mutter 
     /ossssssss/        +ssssooo/-       Terminal: kgx 

```

单选开关的状态和颜色也有毛病.有时候做左边是激活,有时候右边是激活
![image](https://github.com/tuberry/light-dict/assets/1448159/374f18b0-5e62-4762-891c-d76a1c731931)

![截图 2023-11-21 14-46-41](https://github.com/tuberry/light-dict/assets/1448159/e2d7d061-d0d0-4bb2-8977-3ee550c7079f)

**Comment by tuberry** [comment]
~~> 但需要打开显示结果才行.~~

~~这个无法复现。~~

管道支持原本只是为了方便调试写的并不完善（例如这儿管道符`|`不能作为参数），现在所有命令应该一致支持了。
但此处的 sh 命令几乎不支持 [shell expansions](https://www.gnu.org/software/bash/manual/html_node/Shell-Expansions.html)，所以个人使用时推荐将任何复杂的命令包装为可执行脚本放个人目录下使用。
