### ISSUE TITLE
Proactive popup is triggered only when multiple words are selected.

### ISSUE THREAD

**Issue by nbCloud91** [tuberry/light-dict#29]
Proactive mode popup is triggered only when multiple words are selected, and is thus unusable as a dictionary.
Passive mode is working as expected.

**Comment by tuberry** [comment]
Cannot reproduce on GNOME 47 / Firefox. 

Please provide detailed reproduction steps.

**Comment by nbCloud91** [comment]
I am on Gnome 46 (NixOS unstable), and this behavior is seen in all GUI apps including Firefox, Brave, Geary (email), Sioyek (minimal pdf reader). I checked after disabling all other extensions, I still get the same behavior. Furthermore, I stick with default Adwaita theme and do not have any extra theming. Tested this on a setup as close to stock Gnome as possible.

**Comment by tuberry** [comment]
This is a default setting that I forgot to remove during the refactoring.

It could be fixed by removing the `Basic / Other / RegExp filter` setting in the preference page.
