### ISSUE TITLE
Impossible to see all the panel

### ISSUE THREAD

**Issue by Yoannjap** [tuberry/light-dict#3]
Hello,

I really love your extension now!

Just another thing I noticed. With the keyboard shortcut CTRL+Shift+Z that shows the dict command result in a panel, the content of the panel is often too large to be displayed entirely onto my screen.

Could you add the ability to scroll down to see all the results?

Thanks a lot!

Yoannjap

**Comment by tuberry** [comment]
OK ,`dict` may be a bad example. I forget the `dict` result is always long because I create a concise dictionary that does not show too much. 
The problem for me is that  `scroll` relates to a fixed size, it is the height in your situation, which has no problem with long outputs but introduces blanks in short ones. What do you think?
By the way, please close the previous issue if it's solved, thanks. :)

**Comment by Yoannjap** [comment]
Thanks for your answer very interesting.

However, if I understand well, scroll relates to a fixed size to be enabled or not. If this is impossible to apply, why wouldn't it be possible to apply a default size of Full HD resolution or a fixed panel size in pixel and let scrolling enabled whatever your screen size is... ?

PS: I closed the previous issue.

**Comment by tuberry** [comment]
Actually, you need  to know `scrollable` is not an attribute of widget but is widget itself, which works with a fixed size being set. 
I try to keep it simple and flexible, so any fixed things are not attractive for me. (By the way, you can change the shortcut by clicking).
And I make an option `min lines to scroll`, which means a fixed scrollable widget will be used to show result when the output is longer than that. You will see it in next version:
![image](https://user-images.githubusercontent.com/17917040/80850667-a95d7200-8c4f-11ea-93c2-8f3b823f9503.png)

**Comment by tuberry** [comment]
Supported in Version 9

**Comment by deepgai** [comment]
Hi tuberry,
I am trying out this extension (using dict) but this scroll feature seems to be missing. I am on Ubuntu 22.04 with Gnome 42. Is the scroll option available in Gnome 42?
Thanks.

**Comment by tuberry** [comment]
@deepgai  It's conflict with line_warp since 42.  You could comment on this [line](https://github.com/tuberry/light-dict/blob/f853f90dd7d5f1736b1175038d3ece8bab22d787/light-dict%40tuberry.github.io/extension.js#L364) to scroll.

**Comment by deepgai** [comment]
@tuberry Thanks for the tip, I was able to get it to work. Couldn't find the exact issue or change with scrollview in 42 but commenting those lines did the job.
It maybe asking for too much but I was wondering if can be possible to select some of the text in the panel and copy it? e.g. selecting a particular definition from dict. How may I proceed if it requires some change in code?

Thank you for the extension, it is very handy as it can work outside the browser too (pdf, text doc, terminal etc) and while I use it for dictionary, I can imagine how useful it is for translation. 
Cheers.

**Comment by tuberry** [comment]
@deepgai The panel is singleton, and if the text in it is selected, a situation similar to the Ouroboros occurs. The panel will disappear and appear at the current cursor without time to copy. By the way, it could copy all the text by middle-clicking.

If you want similar functionality I would recommend you to use an application instead, if you want to tweak this extension that's not a line or two of code that will do it, it's up to you! :)

**Comment by deepgai** [comment]
@tuberry OK. I may look into it later. I didn't know about middle-clicking to copy, that also helps. 
Thanks and have a good day.
cheers
