### ISSUE TITLE
如果能做成app就太好了

### ISSUE THREAD

**Issue by yueduz** [tuberry/light-dict#30]
gnome插件只能在gnome shell下用,而且一升级就出毛病.软件的交互是完美的,但是以插件形式出下限制了他的发展和用户数量

**Comment by tuberry** [comment]
同功能乃至功能更丰富的 APP 并不少，你可以搜搜看。

此扩展依赖于不少跨应用(合成器级)特权操作，例如全局鼠标位置/修饰键，[剪贴板监听](https://wayland.app/protocols/wlr-data-control-unstable-v1#compositor-support)，[自定义面板](https://wayland.app/protocols/wlr-layer-shell-unstable-v1#compositor-support)等等。它们要么还不存在，要么不会被实现。就 GNOME 而言，上游明确拒绝实现前面两个链接中的协议，因此这样的 APP 更可能在 GNOME 之外的系统（我用的不多）下运行。这大概就是此扩展之所以是扩展的原因。此外，扩展对于用户可能有一个优点：其代码会经专人[审查](https://extensions.gnome.org/about/)。

至于升级出现问题请提 [issue](https://gitlab.com/saalen/ansifilter/-/blob/a6f796b55041ceb49fd4b10167dd9b6ab61b5f39/makefile#L87)。
