### ISSUE TITLE
着色输出

### ISSUE THREAD

**Issue by yueduz** [tuberry/light-dict#4]
我使用ydcv来翻译，他支持着色输出
ydcv  "LDWORD" --color always
```
[4mLDWORD[0m[36m
  Translation:[0m
     * LDWORD
[36m
  Online Resource:[0m
     * [4mhttp://www.ldoceonline.com/search/?q=LDWORD[0m
```
light-dict能不能也支持着色呢

**Comment by tuberry** [comment]
它文档给的控制文本的API不完全有效其中就有颜色控制，并且我不知道该上哪提BUG，所以不行至少暂时不行。

**Comment by tuberry** [comment]
成了，那 BUG 暂时可以忽略。等不及可以从 github 安装。
![image](https://user-images.githubusercontent.com/17917040/86388244-01a00700-bcc7-11ea-911d-42008880ce72.png)
注意命令换成 `ydcv --html -- LDWORD `。这不是终端 ANSI 码没用

**Comment by yueduz** [comment]
ydcv 没有 --html 选项啊，是要更新ydcv还是更新light-dict

**Comment by tuberry** [comment]
安装 [ydcv-rs](https://github.com/farseerfc/ydcv-rs) 或者去上游提需求。
