### ISSUE TITLE
想左键点击气泡复制翻译内容该怎么设置啊?

### ISSUE THREAD

**Issue by yueduz** [tuberry/light-dict#5]

**Comment by tuberry** [comment]
可以用中键复制。左键执行的命令我一般用来发音，如果你一定需要左键复制，可以安装 `xclip` 或者 `wl-clipboard` :
```shell
dict -- LDWORD | xclip -selection clipboard
```

**Comment by yueduz** [comment]
我想要的是翻译结果,不是被翻译的内容

tubery <notifications@github.com> 于2020年8月2日周日 上午10:08写道：

**Comment by yueduz** [comment]
发音又是怎么设置的

**Comment by tuberry** [comment]
我指的就是翻译结果。你那里不是吗？

**Comment by yueduz** [comment]
> 我指的就是翻译结果。你那里不是吗？

是的,是我搞错了

**Comment by tuberry** [comment]
> 发音又是怎么设置的

发音的话可以自己弄音源或者网上的也行。这是我现在用的：
```shell
mpg123 http://dict.youdao.com/dictvoice?audio=LDWORD
```
