### ISSUE TITLE
更新后不好用了,还是原来的按下快捷键弹出好用.

### ISSUE THREAD

**Issue by yueduz** [tuberry/light-dict#6]
现在按键盘成了切换弹出方式了.

**Comment by tuberry** [comment]
额，快捷键我原本就计划用来切换弹出方式的。现在如果触发方式选了键盘你可以按住<kbd>ctrl</kbd>然后点选要翻译的词。当然实在不喜欢可以回退上一个版本

**Comment by yueduz** [comment]
按住ctrl点词弹不出窗口来，触发方式已设为键盘
gnome 3.36.3
Wayland
archlinux

tubery <notifications@github.com> 于2020年8月6日周四 下午8:34写道：

**Comment by tuberry** [comment]
Arch/ gnome-shell 3.36.4/wayland 无法复现
你在 `lg` 中 执行 `global.get_pointer()` 的结果贴一下

**Comment by yueduz** [comment]
![2020-08-06 20-58-38 的屏幕截图](https://user-images.githubusercontent.com/1448159/89534498-a0b8a100-d827-11ea-91f7-4936997953cf.png)

**Comment by tuberry** [comment]
改了一下，你从 github 安装看看能不能用

**Comment by yueduz** [comment]
可以用了，但是还是建议使用原来的模式。现在每划一个字都请求一次。划一句话不知道请求多少次。请求次数过多怕api又被限制。

**Comment by tuberry** [comment]
我不怎么用整句翻译和有道。你暂时用上一个版本吧

**Comment by tuberry** [comment]
刚才应该修复了划句时多次请求的问题，你可以安装看看行不行

**Comment by yueduz** [comment]
行了。键盘触发方式里可不可以再加个子选项，把原来的按下快捷键弹出翻译加进去。另外默认触发方式也应该加个提示，不然都不知道是按哪个键触发。按住ctrl触发会和多个选区快捷键冲突。在vscode和word里，按住ctrl可以选择多个文本区域。

**Comment by tuberry** [comment]
我不准备再加快捷键了，
![image](https://user-images.githubusercontent.com/17917040/89959613-6c9e0f80-dc6f-11ea-9a94-a84e1c94f7a8.png)
各软件对修饰键的处理不尽相同，你可以任选这三个键按

**Comment by tuberry** [comment]
新加了个 DBus 接口，你可以按 [README](https://github.com/tuberry/light-dict/blob/master/README.md) 在系统快捷键那设置

**Comment by yueduz** [comment]
> 新加了个 DBus 接口，你可以按 [README](https://github.com/tuberry/light-dict/blob/master/README.md) 在系统快捷键那设置

那如何禁用原有的三种触发方式?

**Comment by tuberry** [comment]
重构了下，现在可以选择禁用触发方式。
