### ISSUE TITLE
想通过dbus调用进阶命令怎么写？

### ISSUE THREAD

**Issue by yueduz** [tuberry/light-dict#8]
想通过dbus调用进阶命令怎么写？或者我使用dbus打开翻译气泡时能不能也同时显示进阶图标
![2020-09-20 21-53-51 的屏幕截图](https://user-images.githubusercontent.com/1448159/93713063-4469d080-fb8c-11ea-953e-30121c9ec6f7.png)

**Comment by tuberry** [comment]
更新了 README。同时显示两条命令分号隔开即可。
